name: Build
on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md

env:
  IMAGE_NAME: "ghcr.io/wavefrontset/scrapydweb"
  PLATFORMS: "linux/amd64,linux/arm64"

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        PYTHON_VERSION: ["3.13"]
        SCRAPYDWEB_VERSION: ["1.6.0"]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          platforms: ${{ env.PLATFORMS }}
          build-args: |
            PYTHON_VERSION=${{ matrix.PYTHON_VERSION }}
            SCRAPYDWEB_VERSION=${{ matrix.SCRAPYDWEB_VERSION }}
          tags: |
            ${{ env.IMAGE_NAME }}:${{ matrix.SCRAPYDWEB_VERSION }}-py${{ matrix.PYTHON_VERSION }}
          push: true
